import 'package:flutter/material.dart';
import '../../foundation/gen/assets.gen.dart'; // Import the generated Assets class

class ProductImage extends StatelessWidget {
  // 1. Strongly typed input: only accepts AssetGenImage generated by flutter_gen
  // This way, the user cannot pass in an incorrect string path
  final AssetGenImage image;

  final double? width;
  final double? height;
  final BoxFit fit;

  const ProductImage({
    super.key,
    required this.image,
    this.width,
    this.height,
    this.fit = BoxFit.contain,
  });

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    // 2. 基礎渲染
    // flutter_gen automatically handles the package parameter, no need to worry about path issues
    Widget content = image.image(
      width: width,
      height: height,
      fit: fit,
      filterQuality: FilterQuality.medium, // 優化縮放畫質
      package: 'ui_kit_library',
    );

    // 3. Dark mode adaptation (Dimming) - Charter 5.2
    if (isDark) {
      return ColorFiltered(
        // Overlay a 10% black layer to make white device casings less harsh on a dark background
        colorFilter: const ColorFilter.mode(
          Colors.black12,
          BlendMode.darken,
        ),
        child: content,
      );
    }

    return content;
  }
}
