openapi: 3.0.0
info:
  title: UI Kit Interactive Components API
  version: 1.0.0
  description: >
    This is a pseudo-contract defining the public API surface of the new UI Kit components.
    Since this is a Flutter package, these "endpoints" represent Widget Constructors and public methods.

paths:
  /components/AppTextFormField:
    post:
      summary: Constructor for AppTextFormField
      description: Creates a form field that wraps AppTextField.
      requestBody:
        content:
          application/dart:
            schema:
              type: object
              properties:
                label:
                  type: string
                validator:
                  type: string
                  format: function
                onSaved:
                  type: string
                  format: function
  
  /components/AppDropdown:
    post:
      summary: Constructor for AppDropdown
      description: Creates a dropdown selection widget.
      requestBody:
        content:
          application/dart:
            schema:
              type: object
              properties:
                items:
                  type: array
                value:
                  type: object
                onChanged:
                  type: string
                  format: function

  /components/AppLoader:
    post:
      summary: Constructor for AppLoader
      description: Creates a loading indicator.
      requestBody:
        content:
          application/dart:
            schema:
              type: object
              properties:
                variant:
                  type: string
                  enum: [circular, linear]
                value:
                  type: number
                  description: 0.0 to 1.0 for determinate, null for indeterminate.

  /components/AppToast:
    post:
      summary: Constructor for AppToast
      description: Creates a feedback toast widget.
      requestBody:
        content:
          application/dart:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum: [success, error, info, warning]
                title:
                  type: string

  /components/AppListTile:
    post:
      summary: Constructor for AppListTile
      description: Creates a list item tile.
      requestBody:
        content:
          application/dart:
            schema:
              type: object
              properties:
                leading:
                  type: object
                  description: Widget
                title:
                  type: object
                  description: Widget
                trailing:
                  type: object
                  description: Widget
